services:
  postgres:
    image: postgres:16
    container_name: pgtoch-postgres
    environment:
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pgtoch-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: pgtoch-adminer
    restart: always
    ports:
      - "8080:8080"
  
  clickhouse:
    image: clickhouse/clickhouse-server:23.10
    container_name: pgtoch-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ch_data:/var/lib/clickhouse

  tabix:
    image: spoontes/clickhouse-tabix-web-client
    container_name: pgtoch-tabix
    ports:
      - "8124:80"
    depends_on:
      - clickhouse
  

volumes:
  pg_data:
  ch_data:

  